"""exercise demo media

Revision ID: a5ef30473e95
Revises: 695eddde64ac
Create Date: 2026-07-09 23:12:45.881150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ef30473e95'
down_revision: Union[str, Sequence[str], None] = '695eddde64ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('video_url', sa.String(length=500), server_default='', nullable=False))
    op.add_column('exercises', sa.Column('media_path', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'media_path')
    op.drop_column('exercises', 'video_url')
    # ### end Alembic commands ###
